import type { Product, Service, Sector, Project } from '@/lib/types';
import { Camera, ShieldCheck, Wrench, Route, Cpu, Ship, Truck, Bus, Tractor, Construction, Ambulance, Trash2, HardHat, Warehouse, Anchor, Cog } from 'lucide-react';

export const mockServices: Service[] = [
  {
    id: '1',
    title: 'Brigade Sistem Entegrasyonu',
    slug: 'brigade-sistem-entegrasyonu',
    icon: Wrench,
    summary: 'Araçlarınıza özel Brigade güvenlik sistemlerinin profesyonel montaj ve entegrasyonu.',
    content: '<p>ADC Tasarım olarak, Brigade Electronics ürünlerinin yetkili servis ve montaj merkeziyiz. Uzman ekibimiz, her türlü ticari araca ve mobil iş makinesine yönelik kamera monitör sistemleri, radar sensörleri ve mobil dijital kayıt cihazları gibi çözümlerin entegrasyonunu titizlikle gerçekleştirir.</p><p>Sürecimiz, aracınızın ve operasyonel ihtiyaçlarınızın analiziyle başlar. En uygun sistem konfigürasyonunu belirledikten sonra, fabrika standartlarında montaj ve kalibrasyon işlemlerini tamamlarız. Sistemlerin araç elektroniği ile tam uyumlu çalışmasını sağlayarak, maksimum güvenlik ve performans elde etmenizi garanti ederiz.</p>',
  },
  {
    id: '2',
    title: 'Özelleştirilmiş Güvenlik Çözümleri',
    slug: 'ozellestirilmis-guvenlik-cozumleri',
    icon: ShieldCheck,
    summary: 'Filo ve operasyonlarınıza özel, uçtan uca güvenlik ve verimlilik sistemleri tasarlıyoruz.',
    content: '<p>Her filonun ve şantiyenin kendine özgü zorlukları olduğunun farkındayız. Standart çözümlerin yetersiz kaldığı durumlarda, ADC Tasarım\'ın mühendislik birikimi devreye girer. Kör noktaların tamamen ortadan kaldırılması, karmaşık manevra alanlarında tam görüş sağlanması veya özel mobil takip sistemlerinin geliştirilmesi gibi konularda size özel projeler üretiyoruz.</p>',
  },
];

export const mockTechSolutions: Service[] = [
    {
    id: '3',
    title: 'Telematik ve Filo Yönetimi',
    slug: 'telematik-ve-filo-yonetimi',
    icon: Route,
    summary: 'Araç takibi, sürücü davranışı analizi ve operasyonel verimlilik için gelişmiş telematik çözümleri.',
    content: '<p>BRIDGE mobil dijital kayıt cihazları ve telematik altyapısını kullanarak filonuzun tam kontrolünü elinize alın. Araçlarınızın konumunu anlık olarak izleyin, yakıt tüketimini optimize edin, sürücü performansını değerlendirin ve bakım süreçlerini otomatikleştirin. Topladığımız verilerle size özel raporlar sunarak, operasyonel maliyetlerinizi düşürmenize yardımcı oluyoruz.</p>',
  },
  {
    id: '4',
    title: 'Mobil DVR ve Bulut Depolama',
    slug: 'mobil-dvr-ve-bulut-depolama',
    icon: Cpu,
    summary: 'Olay anı görüntülerini anında kaydeden, uzaktan erişilebilir mobil DVR sistemleri.',
    content: '<p>Brigade\'in MDR serisi mobil dijital kayıt cihazları ile kaza anlarını, hırsızlık girişimlerini veya operasyonel hataları saniye saniye kaydedin. 4G bağlantısı sayesinde bu kayıtlara dünyanın her yerinden anında erişin. Otomatik bulut yedekleme çözümlerimizle, kritik verilerinizin güvende olduğundan emin olun.</p>',
  }
];


export const mockSectors: Sector[] = [
  {
    id: '1',
    name: 'Tarım',
    slug: 'tarim',
    icon: Tractor,
    imageUrls: ['sector-agriculture'],
    imageHint: 'tractor field',
    description: 'Tarım, küresel pazarda rekabetçi kalmak için verimliliğin hayati olduğu, kendine özgü zorluklara sahip, oldukça çeşitli bir endüstridir. Verimlilik ve güvenlik arasında bir denge kurma ihtiyacı çok önemlidir.',
    challenges: 'Modern makinelerin tasarımı önemli performans iyileştirmelerine yol açmış olsa da, bu makinelerin doğası ve boyutu operatör görüşünün bozulmasına neden olmaktadır. Kör noktalar, tarım makinelerini içeren birçok kazada katkıda bulunan bir faktördür. Aslında, tarım Avrupa\'daki herhangi bir endüstrinin en kötü ölüm oranına sahiptir. Tarımdaki tüm ölümcül olayların dörtte biri hareketli araçlardan kaynaklanmaktadır.',
    solutionsContent: '<h3>Güvenlik Sistemi Önerileri</h3><p>Doğru cihazları seçmenize yardımcı olmak için her araç için önerilerde bulunduk. Önerilen çözümler arasında <strong>Yükleyici</strong>, <strong>Telehandler</strong>, <strong>Traktör</strong> ve <strong>Biçerdöver</strong> bulunmaktadır.</p><h4>Öne Çıkan Ürünler:</h4><ul><li>Backeye®360 Kamera Monitör Sistemi</li><li>Backsense® Radar</li><li>Geri Vites Alarmı</li><li>Dijital Kayıt Cihazları (MDR)</li></ul>',
  },
  {
    id: '2',
    name: 'Havalimanları',
    slug: 'havalimanlari',
    icon: Ship,
    imageUrls: ['sector-airports'],
    imageHint: 'airport tarmac',
    description: 'Havalimanları, sürekli hareket halinde olan çok çeşitli işletme araçlarının bulunduğu son derece yoğun yerlerdir. Bir havalimanı içindeki birden fazla şirket binlerce kişiyi istihdam etmekte ve her gün binlerce kişi daha seyahat etmektedir.',
    challenges: 'Apronlar potansiyel olarak tüm havaalanı ortamlarının en tehlikelisidir: sıkışık, gürültülü ve çeşitli hızlarda ve yönlerde seyahat eden çeşitli bir araç filosuyla doludur. Sıkı bir programda çalışırken herkesi güvende tutmak karmaşık bir iştir, ancak büyük önem taşır.',
    solutionsContent: '<h3>Havalimanı Güvenliği İçin Çözümler</h3><p>Brigade\'in ticari araç ve tesis güvenlik sistemleri, çoğu havalimanı aracı için uygundur. Bu güvenlik sistemleri arasında ön ve arka görüş kameraları, 360° kameralar, kabin içi monitörler, Sidescan® Predict ultrasonik sensörler, Backsense® Radar tespiti, bbs-tek® geri vites alarmları ve mobil dijital kayıt cihazları bulunur.</p><h4>Öne Çıkan Ürünler:</h4><ul><li>Backeye®360 Kamera Monitör Sistemi</li><li>Backsense® Radar</li><li>Geri Vites Alarmı</li><li>Dijital Kayıt Cihazları (MDR)</li><li>Kameralar ve Monitörler</li></ul>',
  },
  {
    id: '3',
    name: 'Otobüs ve Yolcu Taşımacılığı',
    slug: 'otobus-ve-yolcu-tasimaciligi',
    icon: Bus,
    imageUrls: ['sector-bus'],
    imageHint: 'city bus',
    description: 'Otobüsler, şehirlerarası otobüsler ve minibüsler gibi PSV taşımacılığı ve yolcu taşıyan araçlar, günümüzün yolcuları ve tatilcileri için temel bir hizmet sunmaktadır.',
    challenges: 'Araç boyutları ve sürücü pozisyonları nedeniyle, otobüsler ve yolcu otobüsleri geniş kör noktalara sahiptir. Bu görünürlük eksikliği, olaylara katkıda bulunan bir faktördür ve çarpışma riskini büyük ölçüde artırır. Olayları önleyebilmek ve sahte sigorta taleplerini ve vandalizmi caydırabilmek, yolcuların, personelin ve diğer yol kullanıcılarının güvenliği ile hizmetin güvenilirliği ve verimliliği için önemlidir.',
    solutionsContent: '<h3>Yolcu Taşımacılığı Güvenlik Çözümleri</h3><p>Yolcuların, çalışanların ve halkın güvenliği esastır. Brigade güvenlik sistemleri, olayları önlemeye ve sahte sigorta taleplerini caydırmaya yardımcı olur.</p><h4>Öne Çıkan Ürünler:</h4><ul><li>Backeye®360 Kamera Monitör Sistemi</li><li>Backsense® Radar</li><li>Geri Vites Alarmı</li><li>Dijital Kayıt Cihazları (MDR)</li><li>Kameralar ve Monitörler</li></ul>',
  },
  {
    id: '4',
    name: 'İnşaat',
    slug: 'insaat',
    icon: Construction,
    imageUrls: ['sector-construction'],
    imageHint: 'construction site',
    description: 'İnşaat sahalarında işçi ve araç güvenliği her şeyden önemlidir. Ancak, karayolu ve arazi inşaat araçlarıyla birleşen ağır iş makineleri gerçek bir tehdit oluşturmaktadır.',
    challenges: 'Ortalama olarak, her yıl yedi işçi ölmekte ve 93 kişi ağır yaralanmaktadır. Yavaş hareket eden araçlar, kör noktalar ve zayıf görüş koşullarıyla dolu zorlu ortamlar, dünyanın en yüksek riskli çalışma ortamlarından bazılarını yaratır.',
    solutionsContent: '<h3>İnşaat Güvenliği İçin Çözümler</h3><p>Brigade\'in pazar lideri inşaat aracı güvenlik sistemleri, FORS, CLOCS, HS2 gibi yönetmeliklere uygun olarak olayları durdurmak ve güvenliği artırmak için tasarlanmıştır. 360 derece kamera sistemlerinden beyaz sesli alarmlara kadar geniş ürün yelpazemizi görün.</p><h4>Öne Çıkan Ürünler:</h4><ul><li>Backeye®360 AI Kameralı 360° Sistemler</li><li>Backsense® Radar</li><li>bbs-tek® Beyaz Sesli Geri Vites Alarmı</li><li>Mobil Dijital Kayıt Cihazları (MDR)</li></ul>',
  },
  {
    id: '5',
    name: 'Dağıtım',
    slug: 'dagitim',
    icon: Warehouse,
    imageUrls: ['sector-distribution'],
    imageHint: 'delivery van',
    description: 'Dağıtım endüstrisinin patlama yapması ve eve teslimat ve kurye hizmetlerine olan talebin artmasıyla, teslimat araçlarının verimli ancak güvenli bir şekilde çalışması esastır.',
    challenges: 'Eve teslimat ve kurye hizmetlerindeki artış, verimli ve güvenli operasyon ihtiyacı.',
    solutionsContent: '<p>Teslimat araçlarının verimli ve güvenli bir şekilde çalışmasını sağlamak için kör nokta kameraları ve telematik çözümleri sunuyoruz.</p>',
  },
  {
    id: '6',
    name: 'Acil Durum Hizmetleri',
    slug: 'acil-durum-hizmetleri',
    icon: Ambulance,
    imageUrls: ['sector-emergency'],
    imageHint: 'ambulance lights',
    description: 'Acil servis araçlarının sürücüleri çok sayıda tehlikeyle karşılaşır. Olaylara hızla müdahale etmek, yoğun trafikte ve kalabalık yaya alanlarında yüksek hızlarda gezinmeyi gerektirir.',
    challenges: 'Yoğun trafikte ve kalabalık yaya alanlarında yüksek hızda güvenli sürüş.',
    solutionsContent: '<p>Ambulans, itfaiye gibi acil durum araçlarının olaylara hızlı ve güvenli bir şekilde müdahale etmelerine yardımcı olan özel kamera ve uyarı sistemleri sağlıyoruz.</p>',
  },
  {
    id: '7',
    name: 'Nakliye ve Lojistik',
    slug: 'nakliye-ve-lojistik',
    icon: Truck,
    imageUrls: ['sector-logistics'],
    imageHint: 'truck highway',
    description: 'Nakliye ve lojistik ekonominin bel kemiğidir, ancak ağır yük araçlarının kamuoyundaki algısı zayıftır. Yollara hakim olan ve çarpışmalara, sıkışıklığa ve gürültü kirliliğine neden olan makineler olarak görülürler.',
    challenges: 'Ağır vasıtaların karayollarındaki algısı, çarpışmalar, sıkışıklık ve gürültü kirliliği.',
    solutionsContent: '<p>Ağır vasıtalar için 360 derece görüş sistemleri, yan ve arka sensörler ve akıllı geri vites alarmları ile hem güvenliği artırıyor hem de kamuoyu algısını iyileştiriyoruz.</p>',
  },
  {
    id: '8',
    name: 'Taş Ocağı ve Madencilik',
    slug: 'tas-ocagi-ve-madencilik',
    icon: HardHat,
    imageUrls: ['sector-mining'],
    imageHint: 'mining truck',
    description: 'Maden ve taş ocağı sahalarında çalışanları güvende tutmak zorlu ama gerekli bir görevdir. Sektörler zorlu ortamlarda faaliyet gösterir ve büyük mobil tesisler saha çalışanları için çok gerçek bir tehlike oluşturabilir.',
    challenges: 'Zorlu ortamlar, büyük mobil tesislerin saha çalışanları için oluşturduğu tehlike.',
    solutionsContent: '<p>Maden ve taş ocaklarındaki zorlu koşullar için özel olarak tasarlanmış, en dayanıklı radar ve kamera sistemleri ile işçi güvenliğini sağlıyoruz.</p>',
  },
  {
    id: '9',
    name: 'Çöp ve Atık Yönetimi',
    slug: 'cop-ve-atik-yonetimi',
    icon: Trash2,
    imageUrls: ['sector-waste'],
    imageHint: 'garbage truck',
    description: 'Çöp araçları ve atık kamyonları tipik olarak büyük ve ağırdır, bu da onları normal binek araçlara kıyasla daha az manevra kabiliyetine sahip kılar.',
    challenges: 'Büyük ve ağır araçların manevra kabiliyetinin düşük olması, dar sokaklar.',
    solutionsContent: '<p>Çöp kamyonları için özel olarak geliştirilmiş 360 derece kamera sistemleri, radar sensörleri ve akıllı alarmlar ile kentsel alanlarda güvenliği en üst düzeye çıkarıyoruz.</p>',
  },
  {
    id: '10',
    name: 'Yol İnşaatı',
    slug: 'yol-insaati',
    icon: Construction,
    imageUrls: ['sector-road-construction'],
    imageHint: 'road construction',
    description: 'Yol inşaatı tehlikeli bir meslektir ve çalışmak için en tehlikeli yerlerden biri olarak sıralanır. Yollar daha güvenli ve kayıplar 40 yılı aşkın süredir en düşük seviyede olmasına rağmen, yol işçilerini içeren olaylar artmıştır.',
    challenges: 'Yol işçilerini içeren olaylardaki artış, tehlikeli çalışma ortamı.',
    solutionsContent: '<p>Yol yapım makineleri ve çalışanları için RFID tabanlı güvenlik sistemleri ve 360 derece görüş çözümleri ile olayları önlemeye yardımcı oluyoruz.</p>',
  },
  {
    id: '11',
    name: 'Özel Araçlar',
    slug: 'ozel-araclar',
    icon: Cog,
    imageUrls: ['sector-specialist'],
    imageHint: 'specialist vehicle',
    description: 'Tarım, otoyol inşaatı, taş ocakları, mavi ışık, limanlar ve kamu hizmetleri gibi alanlarda kullanılan özel araçlar ve makineler, kendi özel amaçlarına ve çalışma ortamlarına göre uyarlanmış ısmarlama güvenlik çözümleri gerektirir.',
    challenges: 'Belirli amaç ve çalışma ortamına göre özel güvenlik çözümleri gerekliliği.',
    solutionsContent: '<p>Her bir özel aracın amacına ve çalışma ortamına göre uyarlanmış, ısmarlama güvenlik çözümleri tasarlıyor ve uyguluyoruz.</p>',
  },
  {
    id: '12',
    name: 'Deniz Limanları',
    slug: 'deniz-limanlari',
    icon: Anchor,
    imageUrls: ['sector-seaports'],
    imageHint: 'seaport crane',
    description: 'Liman operasyonlarını verimli ancak güvenli bir şekilde yürütmek zorlu bir iştir. Sürekli hareket eden yükler, araçlar ve tesisler ile limanlardaki araçla ilgili olayların herhangi bir endüstrinin en yükseklerinden biri olması şaşırtıcı değildir.',
    challenges: 'Sürekli hareket eden yükler, araçlar ve tesisler; en yüksek araç kaynaklı olay oranlarından biri.',
    solutionsContent: '<p>Liman operasyonlarındaki her türlü araç için RFID etiketli güvenlik bölgeleri, radar sistemleri ve merkezi kayıt çözümleri ile verimliliği ve güvenliği bir arada sağlıyoruz.</p>',
  }
];

export const mockProducts: Product[] = [
  {
    id: 'product-1',
    name: 'AHD 360° KAMERA SİSTEMİ - BN360-300',
    slug: 'ahd-360-kamera-sistemi-bn360-300',
    partNumber: '5800',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Sürücüye aracın etrafının tam bir \'kuş bakışı\' görünümünü gerçek zamanlı olarak sağlayan akıllı bir kamera monitör sistemidir.',
    longDescription: 'Dört adet ultra geniş açılı kameradan gelen canlı görüntüler, bir elektronik kontrol ünitesi (ECU) tarafından işlenir, birleştirilir ve tek bir görüntü olarak monitöre yansıtılır. Bu sistemler, araç kör noktalarını ortadan kaldırmak ve düşük hızda manevra yapmaya yardımcı olmak için tasarlanmıştır.',
    features: [
      '4 kamera ile 360° tam görüş',
      'Gerçek zamanlı görüntü işleme',
      'Özelleştirilebilir ekran görünümleri',
      'Tetikleyicilerle otomatik görünüm değiştirme (örn: geri vites)',
      'Ağır hizmet tipi, IP69K suya ve toza dayanıklı kameralar'
    ],
    specs: {
      'Voltaj': '12-24Vdc',
      'Kameralar': 'IP69K',
      'ECU Boyutları (GxYxD)': '178 x 113 x 26mm',
      'Kamera Boyutları (GxYxD)': '61 x 50 x 42mm',
      'Video Çıkışı': 'AHD 1.0 ve NTSC',
      'Çalışma Sıcaklığı': '-30 ila +75°C',
      'Standartlar': 'UNECE R10 uyumlu, FCC Onaylı, IC Onaylı'
    },
    warranty: '5 Yıl',
    notes: 'Kurulum için kalibrasyon kiti gereklidir. Monitör ve kamera uzatma kabloları dahil değildir.',
    imageUrls: ['placeholder-1'],
    isFeatured: true,
    relatedSectors: ['nakliye-ve-lojistik', 'insaat', 'cop-ve-atik-yonetimi', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-2',
    name: 'HUMAN FORM RECOGNITION (HFR) 360° SİSTEMİ - VBV-360-1000-AI',
    slug: 'hfr-360-sistemi-vbv-360-1000-ai',
    partNumber: '7524 (Kablolar Dahil), 8123 (Kablolar Hariç)',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Yapay Zeka (AI) teknolojisi ile araç etrafındaki insanları tanır ve sürücüyü sesli ve görsel olarak uyarır.',
    longDescription: 'Bu akıllı sistem, Yapay Zeka (AI) kullanarak araç etrafındaki insanları tanır. Algılanan kişiler, sürücünün monitöründeki 360° görüntünün üzerinde renkli bir kutu içinde gösterilir ve sürücü sesli/görsel olarak uyarılır.',
    features: [
      'Yapay Zeka teknolojisi',
      'Yaya veya bisikletli algılandığında sesli ve görsel uyarılar',
      '1080p HD 360° görüntü',
      '5 görüntüleme modu, 2D veya 3D seçeneği',
      'Monitör üzerinden otomatik kalibrasyon'
    ],
    specs: {
      'Voltaj': '12-24Vdc',
      'Kameralar': 'IP69K',
      'ECU Boyutları (GxYxD)': '140 x 122 x 40mm',
      'Kamera Boyutları (GxYxD)': '140 x 63 x 54mm',
      'Video Çıkışı': 'AHD 2.0 ve CVBS (PAL/NTSC)',
      'Standartlar': 'UNECE R10, UNECE R158 uyumlu, FCC Onaylı, IC Onaylı'
    },
    warranty: '3 Yıl',
    notes: 'Kurulum için kalibrasyon matları gereklidir.',
    imageUrls: ['placeholder-2'],
    isFeatured: true,
    relatedSectors: ['nakliye-ve-lojistik', 'insaat', 'cop-ve-atik-yonetimi', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-3',
    name: 'HUMAN FORM RECOGNITION (HFR) KAMERA',
    slug: 'hfr-kamera',
    partNumber: '7321, 7396',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Ön ve arka kör noktalardaki insanları tanır ve sürücüyü uyarır.',
    longDescription: 'Yapay Zeka kullanarak insan formunu algılayan ve sürücüyü olası bir çarpışma öncesinde görsel ve/veya sesli olarak uyaran aktif kör nokta tespit sistemleridir. Algılanan kişiler, kamera görüntüsü üzerine bindirilmiş renkli bir kutu içinde gösterilir. Görüntü işleme doğrudan kamera ünitesi tarafından yapılır.',
    features: [
      'Yüksek Çözünürlüklü AHD 1080P',
      'Tak ve çalıştır: AI kamera doğrudan Brigade monitörüne ve/veya opsiyonel buzzer\'a bağlanır',
      'Tüm Brigade HD monitörleri ve MDR kayıt cihazları ile uyumlu'
    ],
    specs: {
      'Voltaj': '12-24Vdc',
      'Koruma Sınıfı': 'IP69K',
      'Kamera Boyutları (GxYxD)': '97.5 x 75.3 x 72mm',
      'Çalışma Sıcaklığı': '-20 ila +70°C',
      'Standartlar': 'UNECE R10 uyumlu, CE işaretli, FCC Onaylı'
    },
    warranty: '2 Yıl',
    imageUrls: ['placeholder-3'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'insaat'],
  },
  {
    id: 'product-4',
    name: 'ELITE AHD KAMERA 1080p',
    slug: 'elite-ahd-kamera-1080p',
    partNumber: '6408, 6410',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'En zorlu koşullar için en üst düzey performans sunan yüksek çözünürlüklü kamera.',
    longDescription: 'Orijinal Ekipman Üreticileri (OEM\'ler) ve karoserciler için ilk tercih olan, en zorlu koşullarda istisnai kalite ve tutarlı performans sunan en üst düzey sistemlerdir.',
    features: [
      '1080p yüksek çözünürlük',
      'Ultra düşük ışık performansı için kızılötesi LED\'ler',
      'Mikrofon',
      'Normal/Ayna görünümü'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '126°x69°x144°',
      'Koruma Sınıfı': 'IP69K',
      'Boyutlar (GxYxD)': '86x72x78mm'
    },
    warranty: '5 Yıl',
    imageUrls: ['placeholder-4'],
    isFeatured: true,
    relatedSectors: ['insaat', 'tas-ocagi-ve-madencilik'],
  },
  {
    id: 'product-5',
    name: 'WDR\'li ELITE KAMERA',
    slug: 'wdr-li-elite-kamera',
    partNumber: '1623, 1905, 2871, 4924',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Geniş Dinamik Aralık (WDR) teknolojisine sahip, zorlu ışık koşulları için ideal kamera.',
    longDescription: 'Geliştirilmiş detay için Geniş Dinamik Aralık (WDR) teknolojisine sahip bu kameralar, ultra düşük ışık performansı için 5 Kızılötesi LED, Isıtıcı, Mikrofon gibi özelliklerle donatılmıştır.',
    features: [
      'Geniş Dinamik Aralık (WDR)',
      '5 Kızılötesi LED',
      'Isıtıcı',
      'Mikrofon'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '102°x76°x132° (PAL)',
      'Koruma Sınıfı': 'IP68 (BE-890C için IP69K)',
      'Boyutlar (GxYxD)': '86x72x80mm'
    },
    warranty: '5 Yıl',
    imageUrls: ['placeholder-5'],
    isFeatured: false,
    relatedSectors: ['insaat', 'tas-ocagi-ve-madencilik'],
  },
  {
    id: 'product-6',
    name: 'WDR\'li SHUTTER KAMERA',
    slug: 'wdr-li-shutter-kamera',
    partNumber: '1242',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Otomatik shutter özelliği ile lensi kirden ve hasardan koruyan WDR\'li kamera.',
    longDescription: 'Geniş Dinamik Aralık (WDR) teknolojisine ek olarak, otomatik shutter, ısıtıcı ve mikrofon özelliklerine sahiptir. Özellikle çamurlu ve tozlu ortamlar için idealdir.',
    features: [
      'Geniş Dinamik Aralık (WDR)',
      'Otomatik shutter',
      'Isıtıcı',
      'Mikrofon'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '103°x71°x134°',
      'Koruma Sınıfı': 'IP69K',
      'Boyutlar (GxYxD)': '123x86x80mm'
    },
    warranty: '5 Yıl',
    imageUrls: ['placeholder-6'],
    isFeatured: false,
    relatedSectors: ['insaat', 'tas-ocagi-ve-madencilik', 'cop-ve-atik-yonetimi'],
  },
  {
    id: 'product-7',
    name: 'SELECT AHD KAMERA 1080p',
    slug: 'select-ahd-kamera-1080p',
    partNumber: '5466, 5467, 5470, 5471',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Yüksek kaliteli, güvenilir ve popüler orta sınıf kamera sistemi.',
    longDescription: 'Yüksek kaliteli, güvenilir ve popüler orta sınıf sistemlerdir. 1080p AHD çözünürlük, 4 adet yüksek güçlü kızılötesi LED, mikrofon ve ayna görünümü özellikleri sunar.',
    features: [
      '4 adet yüksek güçlü kızılötesi LED',
      'Mikrofon',
      'Ayna görünümü'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '110°x60°x127°',
      'Koruma Sınıfı': 'IP69K',
      'Boyutlar (GxYxD)': '81x77x70mm'
    },
    warranty: '3 Yıl',
    imageUrls: ['placeholder-7'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'cop-ve-atik-yonetimi'],
  },
  {
    id: 'product-8',
    name: 'SHUTTER KAMERA (Select Serisi)',
    slug: 'select-shutter-kamera',
    partNumber: '2808',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Otomatik shutter ve ısıtıcı özellikli, güvenilir orta sınıf kamera.',
    longDescription: 'Select serisinin bu shutter kamerası, 4 adet yüksek güçlü kızılötesi LED, otomatik shutter, ısıtıcı ve mikrofon özellikleriyle gelir. Zorlu koşullar için uygun maliyetli bir çözümdür.',
    features: [
      '4 adet yüksek güçlü kızılötesi LED',
      'Otomatik Shutter',
      'Isıtıcı',
      'Mikrofon'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '98°x73°x108°',
      'Koruma Sınıfı': 'IP68/IP69K',
      'Boyutlar (GxYxD)': '122x85x82mm'
    },
    warranty: '3 Yıl',
    imageUrls: ['placeholder-8'],
    isFeatured: false,
    relatedSectors: ['insaat', 'cop-ve-atik-yonetimi'],
  },
  {
    id: 'product-9',
    name: 'AHD EYEBALL KAMERA',
    slug: 'ahd-eyeball-kamera',
    partNumber: '7143, 7144, 7145, 7146',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'Kompakt, gömme montajlı "eyeball" kamera.',
    longDescription: 'Gömme montajlı "eyeball" kamera, 5 adet yüksek güçlü kızılötesi LED ve mikrofon özelliklerine sahiptir. Kompakt tasarımı sayesinde estetiğin önemli olduğu uygulamalar için idealdir.',
    features: [
      'Gömme montajlı "eyeball" tasarım',
      '5 adet yüksek güçlü kızılötesi LED',
      'Mikrofon'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '130°x70°x151°',
      'Koruma Sınıfı': 'IP69K',
      'Boyutlar (GxYxD)': '57x42x70mm'
    },
    warranty: '3 Yıl',
    imageUrls: ['placeholder-9'],
    isFeatured: false,
    relatedSectors: ['otobus-ve-yolcu-tasimaciligi', 'dagitim'],
  },
  {
    id: 'product-10',
    name: 'AHD MİNİ KAMERA',
    slug: 'ahd-mini-kamera',
    partNumber: 'DMC-1035, DMC-1031',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'İç mekan kullanımı için yüksek çözünürlüklü mini kamera.',
    longDescription: 'İç mekan kullanımı için tasarlanmış yüksek çözünürlüklü AHD mini kamera.',
    features: [],
    imageUrls: ['placeholder-10'],
    isFeatured: false,
    relatedSectors: ['otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-11',
    name: 'SİLİNDİR KAMERA',
    slug: 'silindir-kamera',
    partNumber: 'VBV-485C, VBV-481C',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: '9 LED\'li, IP69K/IP68 korumalı silindir kamera.',
    longDescription: '9 adet LED\'i bulunan, IP69K/IP68 korumalı, dayanıklı silindir kamera.',
    features: ['9 LED', 'IP69K/IP68 Koruma'],
    imageUrls: ['placeholder-11'],
    isFeatured: false,
    relatedSectors: ['insaat', 'tarim'],
  },
  {
    id: 'product-12',
    name: 'AHD DOME KAMERA',
    slug: 'ahd-dome-kamera',
    partNumber: 'MD-60, MD-61 Serisi',
    category: 'Kamera Monitör Sistemleri',
    shortDescription: 'İç veya dış mekanda kullanılabilen, 150° hareket aralığına sahip dome kamera.',
    longDescription: 'İç veya dış mekanda kullanılabilen, 150° hareket aralığına sahip AHD dome kamera.',
    features: ['150° hareket aralığı'],
    imageUrls: ['placeholder-12'],
    isFeatured: false,
    relatedSectors: ['otobus-ve-yolcu-tasimaciligi', 'depolama'],
  },
  {
    id: 'product-13',
    name: 'BE-970WFM 7" Dörtlü Monitör',
    slug: 'be-970wfm-monitor',
    category: 'Kamera Monitör Sistemleri',
    partNumber: '800, 801',
    shortDescription: 'IP69K korumalı, 4 kamera girişli, 7 inçlik en üst düzey dörtlü monitör.',
    longDescription: 'Zorlu koşullar için tasarlanmış, 7 inçlik, IP69K korumalı, 4 kamera girişli Elite serisi monitör.',
    features: ['7 inç', 'IP69K', '4 kamera girişi'],
    warranty: '5 Yıl',
    imageUrls: ['placeholder-13'],
    isFeatured: false,
    relatedSectors: ['insaat', 'tas-ocagi-ve-madencilik', 'tarim'],
  },
  {
    id: 'product-14',
    name: 'VBV-7104HFM 10.4" Dörtlü Monitör',
    slug: 'vbv-7104hfm-monitor',
    category: 'Kamera Monitör Sistemleri',
    partNumber: '1021',
    shortDescription: 'AHD ve CVBS uyumlu, 4 kamera girişli, 10.4 inçlik geniş ekran monitör.',
    longDescription: 'AHD ve CVBS kameralarla uyumlu, 4 kamera girişli, 10.4 inçlik geniş ekran Select serisi monitör.',
    features: ['10.4 inç', '4 kamera girişi', 'AHD & CVBS uyumlu'],
    warranty: '3 Yıl',
    imageUrls: ['placeholder-14'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-15',
    name: 'VBV-243M 4.3" Ayna Monitör',
    slug: 'vbv-243m-monitor',
    category: 'Kamera Monitör Sistemleri',
    partNumber: '1172',
    shortDescription: 'Mevcut dikiz aynasına takılabilen 4.3 inç dijital ayna monitör.',
    longDescription: 'Mevcut dikiz aynasına kolayca takılabilen, 2 kamera girişli, 4.3 inç boyutunda pratik ayna monitör.',
    features: ['4.3 inç', 'Aynaya takılabilir', '2 kamera girişi'],
    warranty: '1 Yıl',
    imageUrls: ['placeholder-15'],
    isFeatured: false,
    relatedSectors: ['dagitim', 'ozel-araclar'],
  },
  {
    id: 'product-16',
    name: 'MOBİL DİJİTAL KAYIT CİHAZI 600 SERİSİ',
    slug: 'mdr-600-serisi',
    category: 'Kayıt Sistemleri',
    partNumber: 'MDR-644 (8 kanal), MDR-641 (5 kanal)',
    shortDescription: '8 veya 5 kanallı, 4G/WiFi opsiyonlu, SSD tabanlı sağlam mobil DVR.',
    longDescription: 'Araç verilerini ve 16 adede kadar kameradan gelen görüntüleri yakalayabilen sistemlerdir. 4G modellerinde uzaktan erişim ve coğrafi sınırlama (Geo-fencing), dahili GPS ve H.265 görüntü sıkıştırma gibi özellikler sunar.',
    features: [
      '8 veya 5 kanal video girişi',
      '1TB veya 2TB SSD seçenekleri',
      '4G ve WiFi opsiyonları',
      'Uzaktan erişim ve Geo-fencing (4G model)',
      'Dahili GPS',
      'H.265 görüntü sıkıştırma'
    ],
    warranty: '3 Yıl',
    imageUrls: ['placeholder-16'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-17',
    name: 'MOBİL DİJİTAL KAYIT CİHAZI 500 SERİSİ',
    slug: 'mdr-500-serisi',
    category: 'Kayıt Sistemleri',
    partNumber: 'MDR-508 (8 kanal)',
    shortDescription: '8 kanallı, 4G/WiFi opsiyonlu, SSD tabanlı, AHD destekli mobil DVR.',
    longDescription: 'AHD yüksek çözünürlük desteği, dahili GPS ve H.264 sıkıştırma özelliklerine sahip, 8 kanallı, SSD tabanlı kayıt cihazıdır. 1TB veya 2TB SSD, 4G ve WiFi seçenekleri mevcuttur.',
    features: [
      '8 kanal video girişi',
      'AHD Yüksek Çözünürlük',
      '1TB veya 2TB SSD seçenekleri',
      '4G ve WiFi opsiyonları',
      'Dahili GPS',
      'H.264 görüntü sıkıştırma'
    ],
    warranty: '3 Yıl',
    imageUrls: ['placeholder-17'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-18',
    name: 'ARAÇ İÇİ KAMERA (Dash Cam) - DC-204-AI',
    slug: 'dash-cam-dc-204-ai',
    partNumber: 'DC-204-AI',
    category: 'Kayıt Sistemleri',
    shortDescription: 'Yapay Zeka destekli, 4G bağlantılı, ADAS ve sürücü davranışı izleme özellikli çift kameralı sistem.',
    longDescription: 'Yapay Zeka destekli, 4G bağlantılı bu araç içi kamera, hem yolu hem de sürücüyü izler. Şeritten Ayrılma Uyarısı (LDW), İleri Çarpışma Uyarısı (FCW) gibi Gelişmiş Sürücü Destek Sistemleri (ADAS) özelliklerinin yanı sıra sürücü yorgunluğu ve dikkat dağınıklığını da izler.',
    features: [
      'Yapay Zeka destekli ADAS ve Sürücü İzleme',
      '4G bağlantısı ile uzaktan erişim',
      'Şeritten Ayrılma Uyarısı (LDW)',
      'İleri Çarpışma Uyarısı (FCW)',
      'Çift kamera (ön ve iç)',
    ],
    imageUrls: ['placeholder-18'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-19',
    name: 'IP SÜRÜCÜ GÜVENLİK SİSTEMİ (Yapay Zekalı)',
    slug: 'ip-surucu-guvenlik-sistemi-ai',
    partNumber: 'IP-DFC-AI, IP-FFC-AI-01',
    category: 'Sürücü Güvenlik Sistemleri',
    shortDescription: 'Sürücü yorgunluğunu, dikkat dağınıklığını ve şeritten ayrılma gibi riskleri algılayan AI tabanlı sistem.',
    longDescription: 'Bu sistem, sürücü ve yol olmak üzere iki yönlü izleme yapar. Sürücüye bakan kamera (IP-DFC-AI) yorgunluk, esneme, telefon kullanımı gibi durumları algılarken, ileriye bakan kamera (IP-FFC-AI-01) şeritten ayrılma (LDW), takip mesafesi (HMW) ve önden çarpışma (FCW) uyarıları verir. Tehlike Uyarı Ünitesi ile sürücüyü sesli ve görsel olarak uyarır.',
    features: [
        'Sürücü yorgunluğu ve dikkat dağınıklığı tespiti',
        'Telefon kullanımı ve sigara içme tespiti',
        'Şeritten Ayrılma Uyarısı (LDW)',
        'Takip Mesafesi Uyarısı (HMW)',
        'Önden Çarpışma Uyarısı (FCW)',
        'Sesli ve görsel uyarılar',
    ],
    imageUrls: ['placeholder-19'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-20',
    name: 'SÜRÜCÜ GÜVENLİK KAMERASI (DDAW dahil)',
    slug: 'surucu-guvenlik-kamerasi-ddaw',
    partNumber: 'MDSM-22, MDSM-22S-DDAW',
    category: 'Sürücü Güvenlik Sistemleri',
    shortDescription: 'AB GSR yönetmeliğine uygun, sürücü uykululuğu ve dikkatini izleyen kamera sistemi.',
    longDescription: 'MDSM-22 modeli yorgunluk, dikkat dağınıklığı, esneme, telefon kullanımı gibi birçok riskli davranışı algılar. MDSM-22S-DDAW modeli ise özel olarak AB 2019/2144 GSR yönetmeliğinin DDAW (Sürücü Uykululuk ve Dikkat Uyarısı) gerekliliklerine uygun olarak geliştirilmiştir.',
    features: [
        'Sürücü uykululuğu ve dikkat dağınıklığı tespiti',
        'Telefon kullanımı, sigara içme, emniyet kemeri takmama tespiti',
        'AB GSR DDAW yönetmeliğine uygun model seçeneği (MDSM-22S-DDAW)'
    ],
    imageUrls: ['placeholder-20'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'otobus-ve-yolcu-tasimaciligi'],
  },
  {
    id: 'product-21',
    name: 'Sidescan®Flex Ultrasonik Tespit Sistemi',
    slug: 'sidescan-flex-ss-4200w',
    partNumber: 'SS-4200W',
    category: 'Tespit Sistemleri',
    shortDescription: '2.5 metreye kadar esnek yan algılama sağlayan, hıza duyarlı ultrasonik sensör sistemi.',
    longDescription: 'Duran ve hareket eden nesneleri algılayarak sürücüyü uyarır. Özellikle büyük araçların yan kör noktaları için tasarlanmıştır. Hıza duyarlı yapısı sayesinde gereksiz uyarıları önler.',
    features: [
        '2.5 metreye kadar esnek yan algılama',
        'Hıza duyarlı aktivasyon',
        'Sesli ve görsel uyarılar',
        'Gereksiz uyarıları filtreleme özelliği',
    ],
    imageUrls: ['placeholder-21'],
    isFeatured: true,
    relatedSectors: ['cop-ve-atik-yonetimi', 'nakliye-ve-lojistik'],
  },
  {
    id: 'product-22',
    name: 'Radar Predict - Yan Çarpışma Tahmini',
    slug: 'radar-predict-rp-001',
    partNumber: 'RP-001 / RP-010',
    category: 'Tespit Sistemleri',
    shortDescription: 'Yapay Zeka ile bisikletliler için 180° yan çarpışma tahmini yapar ve sürücüyü uyarır.',
    longDescription: 'Bu gelişmiş radar sistemi, aracın yan tarafındaki bisikletlilerin hızını ve yönünü analiz ederek olası bir çarpışmayı öngörür. Sürücüyü sadece gerçek bir risk olduğunda uyararak alarm yorgunluğunu önler.',
    features: [
        'Yapay Zeka ile çarpışma tahmini',
        '180° yan algılama alanı',
        'Bisikletli ve diğer VRU\'ları algılama',
        'Sadece riskli durumlarda uyarı',
    ],
    imageUrls: ['placeholder-22'],
    isFeatured: false,
    relatedSectors: ['otobus-ve-yolcu-tasimaciligi', 'cop-ve-atik-yonetimi'],
  },
  {
    id: 'product-23',
    name: 'Front Radar - Ön Çarpışma Önleme',
    slug: 'front-radar-fr-001',
    partNumber: 'FR-001DVS / FR-001R159',
    category: 'Tespit Sistemleri',
    shortDescription: 'Aracın önündeki korunmasız yol kullanıcılarını (VRU) algılamak için 180° çift radar sistemi.',
    longDescription: 'Aracın önündeki yayalar ve bisikletliler gibi korunmasız yol kullanıcılarını algılamak için tasarlanmış 180 derecelik bir çift radar sistemidir. Çarpışma riski olduğunda sürücüyü uyarır.',
    features: [
        '180° ön algılama',
        'VRU (korunmasız yol kullanıcısı) tespiti',
        'Çift radar sistemi'
    ],
    imageUrls: ['placeholder-23'],
    isFeatured: false,
    relatedSectors: ['nakliye-ve-lojistik', 'insaat'],
  },
  {
    id: 'product-24',
    name: 'Backsense® Programlanabilir Radar',
    slug: 'backsense-programmable-bs-8100',
    partNumber: 'BS-8100',
    category: 'Tespit Sistemleri',
    shortDescription: '60 metreye kadar programlanabilir algılama menziline sahip ağır hizmet tipi radar.',
    longDescription: '60 metreye kadar programlanabilir algılama menziline sahip bu radar, sabit nesneleri veya karoseriyi kalibre etme yeteneği ile özelleştirilmiş algılama alanları sağlar. Ağır hizmet tipi uygulamalar için idealdir.',
    features: [
        '60 metreye kadar programlanabilir algılama',
        'Özelleştirilebilir algılama alanı',
        'Sabit nesneleri eleme özelliği',
        'Ağır hizmet tipi tasarım'
    ],
    imageUrls: ['placeholder-24'],
    isFeatured: false,
    relatedSectors: ['tas-ocagi-ve-madencilik', 'insaat', 'limanlar'],
  },
  {
    id: 'product-25',
    name: 'ZoneSafe® RFID Tespit Sistemi',
    slug: 'zonesafe-rfid',
    partNumber: 'ZS-1000-ECU, ZS-1000-AP',
    category: 'Tespit Sistemleri',
    shortDescription: 'Araçlar, sahadaki personel ve varlıklar arasında 360 derecelik bir tespit bölgesi oluşturan RFID sistemi.',
    longDescription: 'ZoneSafe, araçların etrafında 3 ila 10 metre arasında ayarlanabilen bir algılama bölgesi oluşturmak için RFID teknolojisini kullanır. Bölgeye bir etiket girdiğinde, sürücü sesli ve görsel bir uyarı alır.',
    features: [
        'RFID teknolojisi ile 360° algılama',
        '3-10 metre ayarlanabilir algılama bölgesi',
        'Yaya, sürücü ve varlık etiketleri',
        'Sesli ve görsel uyarılar'
    ],
    imageUrls: ['placeholder-25'],
    isFeatured: false,
    relatedSectors: ['tas-ocagi-ve-madencilik', 'insaat', 'depolama', 'limanlar'],
  },
  {
    id: 'product-26',
    name: 'bbs-tek® BEYAZ SES (WHITE SOUND) Akıllı Alarm',
    slug: 'bbs-tek-akilli-alarm',
    partNumber: 'SA-BBS-107 (87-107 dB), SA-BBS-97 (77-97 dB)',
    category: 'Uyarı Alarmları',
    shortDescription: 'Anında duyulabilen ve sadece tehlike bölgesinde etkili olan, kendi sesini ayarlayabilen geri vites alarmı.',
    longDescription: 'Geleneksel "bip-bip" alarmlarının aksine, bbs-tek® alarmları geniş frekans aralığındaki "şşş" benzeri beyaz sesi kullanır. Bu sesin kaynağı anında tespit edilebilir ve sadece tehlike bölgesinde duyulur, gürültü kirliliğini önler. Akıllı modeller, ses seviyesini ortam gürültüsünün 5-10dB üzerine otomatik olarak ayarlar.',
    features: [
        'Anında yer tespiti sağlayan beyaz ses (White Sound)',
        'Sadece tehlike bölgesinde duyulur, gürültü kirliliğini azaltır',
        'Ortam gürültüsüne göre ses seviyesini otomatik ayarlama (Akıllı model)',
        'IP68 koruma sınıfı',
    ],
    warranty: 'Ömür Boyu',
    imageUrls: ['placeholder-26'],
    isFeatured: true,
    relatedSectors: ['insaat', 'cop-ve-atik-yonetimi', 'tas-ocagi-ve-madencilik'],
  },
  {
    id: 'product-27',
    name: 'QVS - Sessiz Araç Ses Cihazı',
    slug: 'qvs-sessiz-arac-ses-cihazi',
    partNumber: 'QVS-001-75',
    category: 'Uyarı Alarmları',
    shortDescription: 'Elektrikli ve hibrit araçlar için, düşük hızlarda yayaları uyarmak amacıyla motor sesi taklit eder.',
    longDescription: 'Elektrikli ve hibrit araçların sessiz çalışması, yayalar için bir risk oluşturabilir. Brigade QVS, aracın hızına, ivmelenmesine ve direksiyon açısına göre değişen, gerçekçi bir motor sesi üreterek bu riski ortadan kaldırır. UN R138 ve diğer uluslararası standartlara uygundur.',
    features: [
        'Elektrikli/Hibrit araçlar için motor sesi simülasyonu',
        'Aracın hareketlerine göre dinamik ses değişimi',
        'Yayaları ve diğer yol kullanıcılarını uyarır',
        'Uluslararası standartlara uygun',
    ],
    imageUrls: ['placeholder-27'],
    isFeatured: false,
    relatedSectors: ['otobus-ve-yolcu-tasimaciligi', 'cop-ve-atik-yonetimi', 'dagitim'],
  },
  {
    id: 'product-28',
    name: 'Konuşan Geri Vites Alarmı (Gece Vardiyası)',
    slug: 'konusan-alarm-gece-vardiyasi',
    partNumber: 'BC-01(NS)',
    category: 'Uyarı Alarmları',
    shortDescription: '"Ssh! Güvenli bir mesafede durun, araç geri gidiyor..." mesajı ve sesi kesme özelliği.',
    longDescription: 'Gece veya gürültüye duyarlı alanlar için tasarlanmış bu konuşan alarm, "Ssh! Güvenli bir mesafede durun, araç geri gidiyor..." mesajını verir. Geri vitese çift takılarak sesi geçici olarak kesme özelliğine sahiptir.',
    features: [
        'Düşük gürültülü ortamlar için özel mesaj',
        'Sesi geçici olarak kesme özelliği',
        'IP68 koruma sınıfı'
    ],
    imageUrls: ['placeholder-28'],
    isFeatured: false,
    relatedSectors: ['cop-ve-atik-yonetimi', 'dagitim'],
  }
];


export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Büyük Bir Lojistik Firması İçin Filo Güvenlik Modernizasyonu',
    slug: 'lojistik-filo-guvenlik-modernizasyonu',
    clientName: 'Gizli Lojistik A.Ş.',
    sector: 'nakliye-ve-lojistik',
    coverImage: 'placeholder-29',
    imageHint: 'truck fleet',
    challenge: 'Müşterimiz, şehir içi dağıtım yapan çekici ve kamyon filosunda, özellikle sağa dönüşler ve geri manevralar sırasında sık sık küçük çaplı kazalar yaşıyordu. Bu durum hem maddi hasara hem de sigorta maliyetlerinde artışa neden oluyordu.',
    solution: 'Filodaki 50 araca, Brigade Backeye®360 BN360-300 sistemi ve Sidescan®Flex ultrasonik sensörler entegre edildi. Backeye®360, şoförlere manevra sırasında tam bir kuşbakışı görüş sağlarken, Sidescan® sistemi dönüşlerde kör noktaya giren bisikletli ve yayalara karşı sesli uyarı verdi.',
    result: 'Projenin ilk 6 ayında, manevra kaynaklı kaza oranı %85 oranında azaldı. Şoförlerin manevra stresi önemli ölçüde düştü ve sigorta primlerinde düşüş için zemin hazırlandı.',
    usedProducts: ['ahd-360-kamera-sistemi-bn360-300', 'sidescan-flex-ss-4200w'],
  },
  {
    id: '2',
    title: 'Belediye Atık Toplama Araçlarında Yaya Güvenliği Projesi',
    slug: 'belediye-atik-toplama-yaya-guvenligi',
    clientName: 'Anadolu Yakası Belediyesi',
    sector: 'cop-ve-atik-yonetimi',
    coverImage: 'placeholder-30',
    imageHint: 'garbage truck city',
    challenge: 'Belediyenin atık toplama kamyonları, dar sokaklarda ve yoğun yaya trafiğinin olduğu bölgelerde çalışırken ciddi güvenlik riskleri oluşturuyordu. Özellikle aracın arkasında ve yanında çalışan personelin güvenliği en büyük endişeydi.',
    solution: 'Her bir atık toplama aracına, 4 kameralı bir MDR-600 serisi mobil DVR sistemi, aracın arkası ve yanları için özel kameralar ve operatörü sesli olarak uyaran bir bbs-tek® Akıllı Alarm kuruldu. Sistem, araç geri vitese takıldığında otomatik olarak devreye giriyor ve sürücü monitöründe arka kamera görüntüsünü gösteriyordu.',
    result: 'Proje sonrasında, araç çevresindeki iş kazaları sıfıra indirildi. Olası anlaşmazlık durumları için tüm operasyonlar kayıt altına alındı ve halktan gelen şikayetlerin çözümünde video kanıtları kullanıldı.',
    usedProducts: ['mdr-600-serisi', 'bbs-tek-akilli-alarm'],
  },
];

    

    

