import type { Product, Service, Sector, Project } from '@/lib/types';
import { Camera, ShieldCheck, Wrench, Route, Cpu, Ship, Truck, Bus, Tractor, Construction } from 'lucide-react';

export const mockServices: Service[] = [
  {
    id: '1',
    title: 'Brigade Sistem Entegrasyonu',
    slug: 'brigade-sistem-entegrasyonu',
    icon: Wrench,
    summary: 'Araçlarınıza özel Brigade güvenlik sistemlerinin profesyonel montaj ve entegrasyonu.',
    content: '<p>ADC Tasarım olarak, Brigade Electronics ürünlerinin yetkili servis ve montaj merkeziyiz. Uzman ekibimiz, her türlü ticari araca ve mobil iş makinesine yönelik kamera monitör sistemleri, radar sensörleri ve mobil dijital kayıt cihazları gibi çözümlerin entegrasyonunu titizlikle gerçekleştirir.</p><p>Sürecimiz, aracınızın ve operasyonel ihtiyaçlarınızın analiziyle başlar. En uygun sistem konfigürasyonunu belirledikten sonra, fabrika standartlarında montaj ve kalibrasyon işlemlerini tamamlarız. Sistemlerin araç elektroniği ile tam uyumlu çalışmasını sağlayarak, maksimum güvenlik ve performans elde etmenizi garanti ederiz.</p>',
  },
  {
    id: '2',
    title: 'Özelleştirilmiş Güvenlik Çözümleri',
    slug: 'ozellestirilmis-guvenlik-cozumleri',
    icon: ShieldCheck,
    summary: 'Filo ve operasyonlarınıza özel, uçtan uca güvenlik ve verimlilik sistemleri tasarlıyoruz.',
    content: '<p>Her filonun ve şantiyenin kendine özgü zorlukları olduğunun farkındayız. Standart çözümlerin yetersiz kaldığı durumlarda, ADC Tasarım\'ın mühendislik birikimi devreye girer. Kör noktaların tamamen ortadan kaldırılması, karmaşık manevra alanlarında tam görüş sağlanması veya özel mobil takip sistemlerinin geliştirilmesi gibi konularda size özel projeler üretiyoruz.</p>',
  },
];

export const mockTechSolutions: Service[] = [
    {
    id: '3',
    title: 'Telematik ve Filo Yönetimi',
    slug: 'telematik-ve-filo-yonetimi',
    icon: Route,
    summary: 'Araç takibi, sürücü davranışı analizi ve operasyonel verimlilik için gelişmiş telematik çözümleri.',
    content: '<p>BRIDGE mobil dijital kayıt cihazları ve telematik altyapısını kullanarak filonuzun tam kontrolünü elinize alın. Araçlarınızın konumunu anlık olarak izleyin, yakıt tüketimini optimize edin, sürücü performansını değerlendirin ve bakım süreçlerini otomatikleştirin. Topladığımız verilerle size özel raporlar sunarak, operasyonel maliyetlerinizi düşürmenize yardımcı oluyoruz.</p>',
  },
  {
    id: '4',
    title: 'Mobil DVR ve Bulut Depolama',
    slug: 'mobil-dvr-ve-bulut-depolama',
    icon: Cpu,
    summary: 'Olay anı görüntülerini anında kaydeden, uzaktan erişilebilir mobil DVR sistemleri.',
    content: '<p>Brigade\'in MDR serisi mobil dijital kayıt cihazları ile kaza anlarını, hırsızlık girişimlerini veya operasyonel hataları saniye saniye kaydedin. 4G bağlantısı sayesinde bu kayıtlara dünyanın her yerinden anında erişin. Otomatik bulut yedekleme çözümlerimizle, kritik verilerinizin güvende olduğundan emin olun.</p>',
  }
];


export const mockSectors: Sector[] = [
  {
    id: '1',
    name: 'Lojistik ve Taşımacılık',
    slug: 'lojistik-ve-tasimacilik',
    imageUrl: 'sector-logistics',
    imageHint: 'trucks warehouse',
    challenges: 'Kör noktalar, geri manevra kazaları, yük ve araç güvenliği, artan yakıt maliyetleri.',
    solutionsContent: 'Backeye®360 kamera sistemleri ile aracın etrafında 360 derece kuşbakışı görüş sağlayarak manevra kazalarını önlüyoruz. Mobil DVR sistemleri ile yük güvenliğini sağlıyor, telematik çözümlerle rota ve yakıt optimizasyonu sunuyoruz.',
  },
  {
    id: '2',
    name: 'İnşaat ve Hafriyat',
    slug: 'insaat-ve-hafriyat',
    imageUrl: 'sector-construction',
    imageHint: 'construction site',
    challenges: 'Şantiye alanındaki personel ve diğer araçların operatör tarafından fark edilmemesi, zorlu arazi koşullarında manevra zorlukları, ekipman güvenliği.',
    solutionsContent: 'Brigade\'in ultra dayanıklı kamera ve radar sistemleri, en zorlu şantiye koşullarında bile kusursuz çalışır. Sidescan® ve Backscan® radar sensörleri, operatörü sesli ve görsel olarak uyararak kör noktalardaki tehlikeleri bertaraf eder.',
  },
  {
    id: '3',
    name: 'Belediye ve Atık Yönetimi',
    slug: 'belediye-ve-atik-yonetimi',
    imageUrl: 'sector-waste',
    imageHint: 'garbage truck',
    challenges: 'Dar sokaklar, yaya ve bisikletli trafiği, geri manevra sırasında yaşanan kazalar, personel güvenliği.',
    solutionsContent: 'Özellikle çöp kamyonları ve yol süpürme araçları için tasarlanan 360 derece kamera sistemleri ve radar çözümleri, operatörün çevresindeki tüm hareketliliği görmesini sağlar. Bu, özellikle meskun mahallerdeki operasyonlarda kaza riskini minimuma indirir.',
  },
    {
    id: '4',
    name: 'Yolcu Taşımacılığı',
    slug: 'yolcu-tasimaciligi',
    imageUrl: 'sector-bus',
    imageHint: 'city bus',
    challenges: 'Duraklara yanaşma, yolcu indirme-bindirme sırasında güvenlik, şehir içi manevralar, vandalizm.',
    solutionsContent: 'Okul servisleri, şehir içi ve şehirler arası otobüsler için geliştirdiğimiz kamera ve kayıt sistemleri, hem yolcu güvenliğini artırır hem de olası adli durumlarda kanıt niteliği taşır. Kör nokta kameraları, şoförün aracın yan ve arka taraflarını tam olarak görmesini sağlar.',
  },
];

export const mockProducts: Product[] = [
  // 1. Kamera Monitör Sistemleri
  {
    id: 'product-1',
    name: 'AHD 360° KAMERA SİSTEMİ - BN360-300',
    slug: 'ahd-360-kamera-sistemi-bn360-300',
    partNumber: '5800',
    category: '360° Kamera Sistemleri (Backeye®360)',
    shortDescription: 'Sürücüye aracın etrafının tam bir \'kuş bakışı\' görünümünü gerçek zamanlı olarak sağlayan akıllı bir kamera monitör sistemidir.',
    longDescription: 'Dört adet ultra geniş açılı kameradan gelen canlı görüntüler, bir elektronik kontrol ünitesi (ECU) tarafından işlenir, birleştirilir ve tek bir görüntü olarak monitöre yansıtılır. Bu sistemler, araç kör noktalarını ortadan kaldırmak ve düşük hızda manevra yapmaya yardımcı olmak için tasarlanmıştır.',
    features: [
      '4 kamera ile 360° tam görüş',
      'Gerçek zamanlı görüntü işleme',
      'Özelleştirilebilir ekran görünümleri',
      'Tetikleyicilerle otomatik görünüm değiştirme (örn: geri vites)',
      'Ağır hizmet tipi, IP69K suya ve toza dayanıklı kameralar'
    ],
    specs: {
      'Voltaj': '12-24Vdc',
      'Kameralar': 'IP69K',
      'ECU Boyutları (GxYxD)': '178 x 113 x 26mm',
      'Kamera Boyutları (GxYxD)': '61 x 50 x 42mm',
      'Video Çıkışı': 'AHD 1.0 ve NTSC',
      'Çalışma Sıcaklığı': '-30 ila +75°C',
      'Standartlar': 'UNECE R10 uyumlu, FCC Onaylı, IC Onaylı'
    },
    warranty: '5 Yıl',
    notes: 'Kurulum için kalibrasyon kiti gereklidir. Monitör ve kamera uzatma kabloları dahil değildir.',
    imageUrls: ['product-backeye-360-1', 'product-backeye-360-2'],
    isFeatured: true,
    relatedSectors: ['lojistik-ve-tasimacilik', 'insaat-ve-hafriyat', 'belediye-ve-atik-yonetimi', 'yolcu-tasimaciligi'],
  },
  {
    id: 'product-2',
    name: 'HUMAN FORM RECOGNITION (HFR) 360° SİSTEMİ - VBV-360-1000-AI',
    slug: 'hfr-360-sistemi-vbv-360-1000-ai',
    partNumber: '7524 (Kablolar Dahil), 8123 (Kablolar Hariç)',
    category: '360° Kamera Sistemleri (Backeye®360)',
    shortDescription: 'Yapay Zeka (AI) teknolojisi ile araç etrafındaki insanları tanır ve sürücüyü sesli ve görsel olarak uyarır.',
    longDescription: 'Bu akıllı sistem, Yapay Zeka (AI) kullanarak araç etrafındaki insanları tanır. Algılanan kişiler, sürücünün monitöründeki 360° görüntünün üzerinde renkli bir kutu içinde gösterilir ve sürücü sesli/görsel olarak uyarılır.',
    features: [
      'Yapay Zeka teknolojisi',
      'Yaya veya bisikletli algılandığında sesli ve görsel uyarılar',
      '1080p HD 360° görüntü',
      '5 görüntüleme modu, 2D veya 3D seçeneği',
      'Monitör üzerinden otomatik kalibrasyon'
    ],
    specs: {
      'Voltaj': '12-24Vdc',
      'Kameralar': 'IP69K',
      'ECU Boyutları (GxYxD)': '140 x 122 x 40mm',
      'Kamera Boyutları (GxYxD)': '140 x 63 x 54mm',
      'Video Çıkışı': 'AHD 2.0 ve CVBS (PAL/NTSC)',
      'Standartlar': 'UNECE R10, UNECE R158 uyumlu, FCC Onaylı, IC Onaylı'
    },
    warranty: '3 Yıl',
    notes: 'Kurulum için kalibrasyon matları gereklidir.',
    imageUrls: ['product-backeye-360-1', 'product-backeye-360-2'],
    isFeatured: true,
    relatedSectors: ['lojistik-ve-tasimacilik', 'insaat-ve-hafriyat', 'belediye-ve-atik-yonetimi', 'yolcu-tasimaciligi'],
  },
  {
    id: 'product-3',
    name: 'HUMAN FORM RECOGNITION (HFR) KAMERA',
    slug: 'hfr-kamera',
    partNumber: '7321 (Ön), 7396 (Arka)',
    category: 'İnsan Formu Tanıma (HFR) Kameraları',
    shortDescription: 'Ön ve arka kör noktalardaki insanları tanır ve sürücüyü uyarır.',
    longDescription: 'Yapay Zeka kullanarak insan formunu algılayan ve sürücüyü olası bir çarpışma öncesinde görsel ve/veya sesli olarak uyaran aktif kör nokta tespit sistemleridir. Algılanan kişiler, kamera görüntüsü üzerine bindirilmiş renkli bir kutu içinde gösterilir. Görüntü işleme doğrudan kamera ünitesi tarafından yapılır.',
    features: [
      'Yüksek Çözünürlüklü AHD 1080P',
      'Tak ve çalıştır: AI kamera doğrudan Brigade monitörüne ve/veya opsiyonel buzzer\'a bağlanır',
      'Tüm Brigade HD monitörleri ve MDR kayıt cihazları ile uyumlu'
    ],
    specs: {
      'Voltaj': '12-24Vdc',
      'Koruma Sınıfı': 'IP69K',
      'Kamera Boyutları (GxYxD)': '97.5 x 75.3 x 72mm',
      'Çalışma Sıcaklığı': '-20 ila +70°C',
      'Standartlar': 'UNECE R10 uyumlu, CE işaretli, FCC Onaylı'
    },
    warranty: '2 Yıl',
    imageUrls: ['product-sidescan-1'],
    isFeatured: false,
    relatedSectors: ['lojistik-ve-tasimacilik', 'insaat-ve-hafriyat'],
  },
  {
    id: 'product-4',
    name: 'ELITE AHD KAMERA 1080p',
    slug: 'elite-ahd-kamera-1080p',
    partNumber: '6408 (PAL), 6410 (NTSC)',
    category: 'Elite Serisi Kameralar',
    shortDescription: 'En zorlu koşullar için en üst düzey performans sunan yüksek çözünürlüklü kamera.',
    longDescription: 'Orijinal Ekipman Üreticileri (OEM\'ler) ve karoserciler için ilk tercih olan, en zorlu koşullarda istisnai kalite ve tutarlı performans sunan en üst düzey sistemlerdir.',
    features: [
      '1080p yüksek çözünürlük',
      'Ultra düşük ışık performansı için kızılötesi LED\'ler',
      'Mikrofon',
      'Normal/Ayna görünümü'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '126°x69°x144°',
      'Koruma Sınıfı': 'IP69K',
      'Boyutlar (GxYxD)': '86x72x78mm'
    },
    warranty: '5 Yıl',
    imageUrls: ['product-backeye-360-1'],
    isFeatured: true,
    relatedSectors: ['insaat-ve-hafriyat'],
  },
  {
    id: 'product-5',
    name: 'SELECT AHD KAMERA 1080p',
    slug: 'select-ahd-kamera-1080p',
    partNumber: '5466',
    category: 'Select Serisi Kameralar',
    shortDescription: 'Yüksek kaliteli, güvenilir ve popüler orta sınıf kamera sistemi.',
    longDescription: 'Yüksek kaliteli, güvenilir ve popüler orta sınıf sistemlerdir. 1080p AHD çözünürlük sunar.',
    features: [
      '4 adet yüksek güçlü kızılötesi LED',
      'Mikrofon',
      'Ayna görünümü'
    ],
    specs: {
      'Görüş Açısı (YxDxD)': '110°x60°x127°',
      'Koruma Sınıfı': 'IP69K',
      'Boyutlar (GxYxD)': '81x77x70mm'
    },
    warranty: '3 Yıl',
    imageUrls: ['product-backeye-360-1'],
    isFeatured: false,
    relatedSectors: ['lojistik-ve-tasimacilik', 'belediye-ve-atik-yonetimi'],
  },
  {
    id: 'product-6',
    name: 'MOBİL DİJİTAL KAYIT CİHAZI 600 SERİSİ',
    slug: 'mdr-600-serisi',
    partNumber: 'MDR-644 (8 kanal), MDR-641 (5 kanal)',
    category: 'Kayıt Sistemleri',
    shortDescription: '8 veya 5 kanallı, 4G/WiFi opsiyonlu, SSD tabanlı sağlam mobil DVR.',
    longDescription: 'Araç verilerini ve 16 adede kadar kameradan gelen görüntüleri yakalayabilen sistemlerdir. 4G modellerinde uzaktan erişim ve coğrafi sınırlama (Geo-fencing), dahili GPS ve H.265 görüntü sıkıştırma gibi özellikler sunar.',
    features: [
      '8 veya 5 kanal video girişi',
      '1TB veya 2TB SSD seçenekleri',
      '4G ve WiFi opsiyonları',
      'Uzaktan erişim ve Geo-fencing (4G model)',
      'Dahili GPS',
      'H.265 görüntü sıkıştırma'
    ],
    warranty: '3 Yıl',
    imageUrls: ['product-mdr-508-1'],
    isFeatured: false,
    relatedSectors: ['lojistik-ve-tasimacilik', 'yolcu-tasimaciligi'],
  },
   {
    id: 'product-7',
    name: 'ARAÇ İÇİ KAMERA (Dash Cam) - DC-204-AI',
    slug: 'dash-cam-dc-204-ai',
    partNumber: 'DC-204-AI',
    category: 'Kayıt Sistemleri',
    shortDescription: 'Yapay Zeka destekli, 4G bağlantılı, ADAS ve sürücü davranışı izleme özellikli çift kameralı sistem.',
    longDescription: 'Yapay Zeka destekli, 4G bağlantılı bu araç içi kamera, hem yolu hem de sürücüyü izler. Şeritten Ayrılma Uyarısı (LDW), İleri Çarpışma Uyarısı (FCW) gibi Gelişmiş Sürücü Destek Sistemleri (ADAS) özelliklerinin yanı sıra sürücü yorgunluğu ve dikkat dağınıklığını da izler.',
    features: [
      'Yapay Zeka destekli ADAS ve Sürücü İzleme',
      '4G bağlantısı ile uzaktan erişim',
      'Şeritten Ayrılma Uyarısı (LDW)',
      'İleri Çarpışma Uyarısı (FCW)',
      'Çift kamera (ön ve iç)',
    ],
    imageUrls: ['product-sidescan-2'],
    isFeatured: false,
    relatedSectors: ['lojistik-ve-tasimacilik', 'yolcu-tasimaciligi'],
  },
  {
    id: 'product-8',
    name: 'IP SÜRÜCÜ GÜVENLİK SİSTEMİ (Yapay Zekalı)',
    slug: 'ip-surucu-guvenlik-sistemi-ai',
    partNumber: 'IP-DFC-AI, IP-FFC-AI-01',
    category: 'Sürücü Güvenlik Sistemleri',
    shortDescription: 'Sürücü yorgunluğunu, dikkat dağınıklığını ve şeritten ayrılma gibi riskleri algılayan AI tabanlı sistem.',
    longDescription: 'Bu sistem, sürücü ve yol olmak üzere iki yönlü izleme yapar. Sürücüye bakan kamera (IP-DFC-AI) yorgunluk, esneme, telefon kullanımı gibi durumları algılarken, ileriye bakan kamera (IP-FFC-AI-01) şeritten ayrılma (LDW), takip mesafesi (HMW) ve önden çarpışma (FCW) uyarıları verir. Tehlike Uyarı Ünitesi ile sürücüyü sesli ve görsel olarak uyarır.',
    features: [
        'Sürücü yorgunluğu ve dikkat dağınıklığı tespiti',
        'Telefon kullanımı ve sigara içme tespiti',
        'Şeritten Ayrılma Uyarısı (LDW)',
        'Takip Mesafesi Uyarısı (HMW)',
        'Önden Çarpışma Uyarısı (FCW)',
        'Sesli ve görsel uyarılar',
    ],
    imageUrls: ['product-sidescan-2'],
    isFeatured: false,
    relatedSectors: ['lojistik-ve-tasimacilik', 'yolcu-tasimaciligi'],
  },
  {
    id: 'product-9',
    name: 'Sidescan®Flex Ultrasonik Tespit Sistemi',
    slug: 'sidescan-flex-ss-4200w',
    partNumber: 'SS-4200W',
    category: 'Tespit Sistemleri',
    shortDescription: '2.5 metreye kadar esnek yan algılama sağlayan, hıza duyarlı ultrasonik sensör sistemi.',
    longDescription: 'Duran ve hareket eden nesneleri algılayarak sürücüyü uyarır. Özellikle büyük araçların yan kör noktaları için tasarlanmıştır. Hıza duyarlı yapısı sayesinde gereksiz uyarıları önler.',
    features: [
        '2.5 metreye kadar esnek yan algılama',
        'Hıza duyarlı aktivasyon',
        'Sesli ve görsel uyarılar',
        'Gereksiz uyarıları filtreleme özelliği',
    ],
    imageUrls: ['product-sidescan-1'],
    isFeatured: true,
    relatedSectors: ['belediye-ve-atik-yonetimi', 'lojistik-ve-tasimacilik'],
  },
  {
    id: 'product-10',
    name: 'Radar Predict - Yan Çarpışma Tahmini',
    slug: 'radar-predict-rp-001',
    partNumber: 'RP-001 / RP-010',
    category: 'Tespit Sistemleri',
    shortDescription: 'Yapay Zeka ile bisikletliler için 180° yan çarpışma tahmini yapar ve sürücüyü uyarır.',
    longDescription: 'Bu gelişmiş radar sistemi, aracın yan tarafındaki bisikletlilerin hızını ve yönünü analiz ederek olası bir çarpışmayı öngörür. Sürücüyü sadece gerçek bir risk olduğunda uyararak alarm yorgunluğunu önler.',
    features: [
        'Yapay Zeka ile çarpışma tahmini',
        '180° yan algılama alanı',
        'Bisikletli ve diğer VRU\'ları algılama',
        'Sadece riskli durumlarda uyarı',
    ],
    imageUrls: ['product-sidescan-1'],
    isFeatured: false,
    relatedSectors: ['yolcu-tasimaciligi', 'belediye-ve-atik-yonetimi'],
  },
  {
    id: 'product-11',
    name: 'bbs-tek® BEYAZ SES (WHITE SOUND) Akıllı Alarm',
    slug: 'bbs-tek-akilli-alarm',
    partNumber: 'SA-BBS-107',
    category: 'Uyarı Alarmları',
    shortDescription: 'Anında duyulabilen ve sadece tehlike bölgesinde etkili olan, kendi sesini ayarlayabilen geri vites alarmı.',
    longDescription: 'Geleneksel "bip-bip" alarmlarının aksine, bbs-tek® alarmları geniş frekans aralığındaki "şşş" benzeri beyaz sesi kullanır. Bu sesin kaynağı anında tespit edilebilir ve sadece tehlike bölgesinde duyulur, gürültü kirliliğini önler. Akıllı modeller, ses seviyesini ortam gürültüsünün 5-10dB üzerine otomatik olarak ayarlar.',
    features: [
        'Anında yer tespiti sağlayan beyaz ses (White Sound)',
        'Sadece tehlike bölgesinde duyulur, gürültü kirliliğini azaltır',
        'Ortam gürültüsüne göre ses seviyesini otomatik ayarlama (Akıllı model)',
        'IP68 koruma sınıfı',
    ],
    warranty: 'Ömür Boyu',
    imageUrls: ['product-sidescan-2'],
    isFeatured: true,
    relatedSectors: ['insaat-ve-hafriyat', 'belediye-ve-atik-yonetimi'],
  },
  {
    id: 'product-12',
    name: 'QVS - Sessiz Araç Ses Cihazı',
    slug: 'qvs-sessiz-arac-ses-cihazi',
    partNumber: 'QVS-001-75',
    category: 'Uyarı Alarmları',
    shortDescription: 'Elektrikli ve hibrit araçlar için, düşük hızlarda yayaları uyarmak amacıyla motor sesi taklit eder.',
    longDescription: 'Elektrikli ve hibrit araçların sessiz çalışması, yayalar için bir risk oluşturabilir. Brigade QVS, aracın hızına, ivmelenmesine ve direksiyon açısına göre değişen, gerçekçi bir motor sesi üreterek bu riski ortadan kaldırır. UN R138 ve diğer uluslararası standartlara uygundur.',
    features: [
        'Elektrikli/Hibrit araçlar için motor sesi simülasyonu',
        'Aracın hareketlerine göre dinamik ses değişimi',
        'Yayaları ve diğer yol kullanıcılarını uyarır',
        'Uluslararası standartlara uygun',
    ],
    imageUrls: ['product-sidescan-2'],
    isFeatured: false,
    relatedSectors: ['yolcu-tasimaciligi', 'belediye-ve-atik-yonetimi'],
  }
];

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Büyük Bir Lojistik Firması İçin Filo Güvenlik Modernizasyonu',
    slug: 'lojistik-filo-guvenlik-modernizasyonu',
    clientName: 'Gizli Lojistik A.Ş.',
    sector: 'lojistik-ve-tasimacilik',
    coverImage: 'project-logistics-1',
    imageHint: 'truck fleet',
    challenge: 'Müşterimiz, şehir içi dağıtım yapan çekici ve kamyon filosunda, özellikle sağa dönüşler ve geri manevralar sırasında sık sık küçük çaplı kazalar yaşıyordu. Bu durum hem maddi hasara hem de sigorta maliyetlerinde artışa neden oluyordu.',
    solution: 'Filodaki 50 araca, Brigade Backeye®360 BN360-300 sistemi ve Sidescan®Flex ultrasonik sensörler entegre edildi. Backeye®360, şoförlere manevra sırasında tam bir kuşbakışı görüş sağlarken, Sidescan® sistemi dönüşlerde kör noktaya giren bisikletli ve yayalara karşı sesli uyarı verdi.',
    result: 'Projenin ilk 6 ayında, manevra kaynaklı kaza oranı %85 oranında azaldı. Şoförlerin manevra stresi önemli ölçüde düştü ve sigorta primlerinde düşüş için zemin hazırlandı.',
    usedProducts: ['ahd-360-kamera-sistemi-bn360-300', 'sidescan-flex-ss-4200w'],
  },
  {
    id: '2',
    title: 'Belediye Atık Toplama Araçlarında Yaya Güvenliği Projesi',
    slug: 'belediye-atik-toplama-yaya-guvenligi',
    clientName: 'Anadolu Yakası Belediyesi',
    sector: 'belediye-ve-atik-yonetimi',
    coverImage: 'project-waste-1',
    imageHint: 'garbage truck city',
    challenge: 'Belediyenin atık toplama kamyonları, dar sokaklarda ve yoğun yaya trafiğinin olduğu bölgelerde çalışırken ciddi güvenlik riskleri oluşturuyordu. Özellikle aracın arkasında ve yanında çalışan personelin güvenliği en büyük endişeydi.',
    solution: 'Her bir atık toplama aracına, 4 kameralı bir MDR-600 serisi mobil DVR sistemi, aracın arkası ve yanları için özel kameralar ve operatörü sesli olarak uyaran bir bbs-tek® Akıllı Alarm kuruldu. Sistem, araç geri vitese takıldığında otomatik olarak devreye giriyor ve sürücü monitöründe arka kamera görüntüsünü gösteriyordu.',
    result: 'Proje sonrasında, araç çevresindeki iş kazaları sıfıra indirildi. Olası anlaşmazlık durumları için tüm operasyonlar kayıt altına alındı ve halktan gelen şikayetlerin çözümünde video kanıtları kullanıldı.',
    usedProducts: ['mdr-600-serisi', 'bbs-tek-akilli-alarm'],
  },
];
